import type { ComparisonResult, ComparisonRow, BenchRunResult } from "@sorobench/runner";

export function formatGithubComment(
  comparisons: ComparisonResult[],
  baseTag?: string,
  headTag?: string,
): string {
  const lines: string[] = [];

  lines.push(`## \u26A1 SoroBench \u2014 Benchmark Diff${baseTag || headTag ? ` (${baseTag ?? "base"} \u2192 ${headTag ?? "head"})` : ""}`);
  lines.push("");

  for (const comp of comparisons) {
    lines.push(`### ${comp.contractName}`);
    lines.push("");
    lines.push("| Function | Before | After | Delta | Change |");
    lines.push("|----------|--------|-------|-------|--------|");

    for (const row of comp.rows) {
      const indicator = row.status === "regressed" ? "\u26A0\uFE0F" : row.status === "improved" ? "\u2705" : "\u2796";
      const changeStr = `${row.changePct >= 0 ? "+" : ""}${row.changePct.toFixed(2)}%`;
      lines.push(
        `| ${row.functionName} | ${formatNum(row.before)} | ${formatNum(row.after)} | ${formatDelta(row.delta)} | ${indicator} ${changeStr} |`,
      );
    }
    lines.push("");

    if (comp.passed) {
      lines.push(`\u2705 **All benchmarks within the ${comp.threshold}% threshold.**`);
    } else {
      const regressed = comp.rows.filter((r) => r.status === "regressed");
      lines.push(
        `\u26A0\uFE0F **${regressed.length} function(s) regressed beyond the ${comp.threshold}% threshold.**`,
      );
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("_Generated by SoroBench v0.1.0_");

  return lines.join("\n");
}

function formatNum(n: number): string {
  if (n >= 1_000_000) {
    return `${(n / 1_000_000).toFixed(2)}M`;
  }
  if (n >= 1_000) {
    return `${(n / 1_000).toFixed(1)}K`;
  }
  return n.toLocaleString();
}

function formatDelta(n: number): string {
  const sign = n >= 0 ? "+" : "";
  return `${sign}${n.toLocaleString()}`;
}
